import { Patient } from "../types";

export const mockPatients: Patient[] = [
  {
    id: "P001",
    name: "Rajesh Kumar",
    age: 45,
    gender: "Male",
    condition: "Hypertension",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-01-15",
    bloodGroup: "O+",
    contact: "+91 98765 43210",
  },
  {
    id: "P002",
    name: "Anita Deshmukh",
    age: 32,
    gender: "Female",
    condition: "Type 2 Diabetes",
    status: "Active",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-02-01",
    bloodGroup: "A-",
    contact: "+91 87654 32109",
  },
  {
    id: "P003",
    name: "Vikram Singh",
    age: 58,
    gender: "Male",
    condition: "Post-op Recovery",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-03-10",
    bloodGroup: "B+",
    contact: "+91 76543 21098",
  },
  {
    id: "P004",
    name: "Sunita Reddy",
    age: 27,
    gender: "Female",
    condition: "Acute Appendicitis",
    status: "Critical",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-25",
    bloodGroup: "AB+",
    contact: "+91 65432 10987",
  },
  {
    id: "P005",
    name: "Mohit Malhotra",
    age: 50,
    gender: "Male",
    condition: "Chronic Bronchitis",
    status: "Active",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-20",
    bloodGroup: "O-",
    contact: "+91 54321 09876",
  },
  {
    id: "P006",
    name: "Sonia Gupta",
    age: 39,
    gender: "Female",
    condition: "Asthma",
    status: "Stable",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-15",
    bloodGroup: "A+",
    contact: "+91 43210 98765",
  },
  {
    id: "P007",
    name: "Amit Patel",
    age: 62,
    gender: "Male",
    condition: "Cardiovascular Disease",
    status: "Critical",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-28",
    bloodGroup: "B-",
    contact: "+91 32109 87654",
  },
  {
    id: "P008",
    name: "Pooja Hegde",
    age: 24,
    gender: "Female",
    condition: "Fever & Fatigue",
    status: "Stable",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-30",
    bloodGroup: "O+",
    contact: "+91 21098 76543",
  },
  {
    id: "P009",
    name: "Suresh Raina",
    age: 41,
    gender: "Male",
    condition: "Knee Surgery",
    status: "Active",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-12",
    bloodGroup: "AB-",
    contact: "+91 10987 65432",
  },
  {
    id: "P010",
    name: "Meera Nair",
    age: 35,
    gender: "Female",
    condition: "Migraine",
    status: "Stable",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-22",
    bloodGroup: "B+",
    contact: "+91 99887 76655",
  },
  {
    id: "P011",
    name: "Arjun Kapoor",
    age: 29,
    gender: "Male",
    condition: "Fractured Arm",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-26",
    bloodGroup: "A+",
    contact: "+91 88776 65544",
  },
  {
    id: "P012",
    name: "Kavita Iyer",
    age: 48,
    gender: "Female",
    condition: "Pneumonia",
    status: "Active",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-18",
    bloodGroup: "O-",
    contact: "+91 77665 54433",
  },
  {
    id: "P013",
    name: "Rahul Bose",
    age: 55,
    gender: "Male",
    condition: "Kidney Stones",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-05",
    bloodGroup: "B-",
    contact: "+91 66554 43322",
  },
  {
    id: "P014",
    name: "Deepika Padukone",
    age: 37,
    gender: "Female",
    condition: "Anxiety Disorder",
    status: "Stable",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-29",
    bloodGroup: "A-",
    contact: "+91 55443 32211",
  },
  {
    id: "P015",
    name: "Virat Kohli",
    age: 34,
    gender: "Male",
    condition: "Sports Injury",
    status: "Active",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-27",
    bloodGroup: "O+",
    contact: "+91 44332 21100",
  },
  {
    id: "P016",
    name: "Anushka Sharma",
    age: 33,
    gender: "Female",
    condition: "Routine Checkup",
    status: "Discharged",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-10",
    bloodGroup: "B+",
    contact: "+91 33221 10099",
  },
  {
    id: "P017",
    name: "MS Dhoni",
    age: 42,
    gender: "Male",
    condition: "Back Pain",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-14",
    bloodGroup: "AB+",
    contact: "+91 22110 09988",
  },
  {
    id: "P018",
    name: "Jasprit Bumrah",
    age: 30,
    gender: "Male",
    condition: "Shoulder Strain",
    status: "Active",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-23",
    bloodGroup: "A+",
    contact: "+91 11009 98877",
  },
  {
    id: "P019",
    name: "Smriti Mandhana",
    age: 27,
    gender: "Female",
    condition: "Wrist Injury",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-19",
    bloodGroup: "O-",
    contact: "+91 00998 87766",
  },
  {
    id: "P020",
    name: "Rohit Sharma",
    age: 36,
    gender: "Male",
    condition: "Hamstring Pull",
    status: "Active",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-24",
    bloodGroup: "B-",
    contact: "+91 99880 07766",
  },
  {
    id: "P021",
    name: "Harmanpreet Kaur",
    age: 34,
    gender: "Female",
    condition: "Influenza",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-21",
    bloodGroup: "AB-",
    contact: "+91 88770 06655",
  }
];

export const analyticsData = {
  monthlyAdmissions: [
    { month: "Jan", patients: 40 },
    { month: "Feb", patients: 55 },
    { month: "Mar", patients: 48 },
    { month: "Apr", patients: 70 },
    { month: "May", patients: 65 },
    { month: "Jun", patients: 82 },
  ],
  conditionBreakdown: [
    { name: "Hypertension", value: 30 },
    { name: "Diabetes", value: 25 },
    { name: "Cardiac", value: 20 },
    { name: "Respiratory", value: 15 },
    { name: "Injury", value: 10 },
  ],
  genderDistribution: [
    { name: "Male", value: 55 },
    { name: "Female", value: 42 },
    { name: "Other", value: 3 },
  ],
};
