import { Patient } from "../types";

export const mockPatients: Patient[] = [
  {
    id: "P001",
    name: "Rajesh Kumar",
    age: 45,
    gender: "Male",
    condition: "Hypertension",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-01-15",
    bloodGroup: "O+",
    contact: "+91 98765 43210",
  },
  {
    id: "P002",
    name: "Anita Deshmukh",
    age: 32,
    gender: "Female",
    condition: "Type 2 Diabetes",
    status: "Active",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-02-01",
    bloodGroup: "A-",
    contact: "+91 87654 32109",
  },
  {
    id: "P003",
    name: "Vikram Singh",
    age: 58,
    gender: "Male",
    condition: "Post-op Recovery",
    status: "Stable",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-03-10",
    bloodGroup: "B+",
    contact: "+91 76543 21098",
  },
  {
    id: "P004",
    name: "Sunita Reddy",
    age: 27,
    gender: "Female",
    condition: "Acute Appendicitis",
    status: "Critical",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-25",
    bloodGroup: "AB+",
    contact: "+91 65432 10987",
  },
  {
    id: "P005",
    name: "Mohit Malhotra",
    age: 50,
    gender: "Male",
    condition: "Chronic Bronchitis",
    status: "Active",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-20",
    bloodGroup: "O-",
    contact: "+91 54321 09876",
  },
  {
    id: "P006",
    name: "Sonia Gupta",
    age: 39,
    gender: "Female",
    condition: "Asthma",
    status: "Stable",
    doctor: "Dr. Arun Varma",
    admissionDate: "2024-04-15",
    bloodGroup: "A+",
    contact: "+91 43210 98765",
  },
  {
    id: "P007",
    name: "Amit Patel",
    age: 62,
    gender: "Male",
    condition: "Cardiovascular Disease",
    status: "Critical",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2024-04-28",
    bloodGroup: "B-",
    contact: "+91 32109 87654",
  }
];

export const analyticsData = {
  monthlyAdmissions: [
    { month: "Jan", patients: 40 },
    { month: "Feb", patients: 55 },
    { month: "Mar", patients: 48 },
    { month: "Apr", patients: 70 },
    { month: "May", patients: 65 },
    { month: "Jun", patients: 82 },
  ],
  conditionBreakdown: [
    { name: "Hypertension", value: 30 },
    { name: "Diabetes", value: 25 },
    { name: "Cardiac", value: 20 },
    { name: "Respiratory", value: 15 },
    { name: "Others", value: 10 },
  ],
  genderDistribution: [
    { name: "Male", value: 55 },
    { name: "Female", value: 42 },
    { name: "Other", value: 3 },
  ],
};
